---
title: "머신러닝(Feat. 패스트캠퍼스)"
output: html_notebook
---

1.  **학습 --\> 지도학습(강화학습) / 비지도 학습(unsupervised learning)**

#### **지도학습**(Supervised learning)이란 정답이 있는 데이터 분석이다.

Labeling(라벨링) 되어 있는 데이터를 분석하는 것이다. 라벨링이 되어 있는 데이터를 이용해서 모형을 만든다. 그 후에 새로운 데이터를 만들어 이 데이터가 어떤 라벨링으로 들어갈 것인지 판단한다.

-   지도학습 -\> 분류 / 비지도학습 -\> 군집화

2.  지도학습에 필요한 개념

-   데이터전처리 : 단위가 다르면 비교 하기 힘들다. 그래서 해결방법으로 표준화!!

    -   표준화(standardization) = 원 데이터 - 평균 / 표준편차 --\> 평균 0, 표준편차 1

    -   Minmax 스케일 = 원 데이터 - min(데이터) / max(데이터) - min(데이터) --\> 0 과 1사이로 데이터 위치!

    -   자료가 연속형인 경우 단위가 다르다? --\> 표준화 또는 Minmax 스케일을 사용한다!!

-   모형평가 : 모형이 좋다? / 나쁘다?

    -   모형평가 할 때 범주형 종속변수, 연속형 종속변수에 따라 달라진다.

    -   범주형 종속변수 --\> ROC 커브 / 연속형 종속변수 --\> MSE(mean squared error) 평균 제곱 오차

    ```{=html}
    <!-- -->
    ```
        -    ROC 커브 -- 여러가지 평가 개념이 있다. ex) 정확도, 에러율, 민감도, 정밀도, False Positive Rate

    -   ROC커브(Receiver operating characteristic, 수신자 조작 특성)

        -   곡선 아래의 면적(AUC= Area Under ROC Curve)이 넓을수록 좋은 모델이다. 1에 가까울 수록 좋다.

    -   MSE(평균제곱 오차) --\> 평균 / 제곱 / 오차

-   오버피팅(overfitting)

    -   모델링의 목적은 일반화

    <!-- -->

    -   오버피팅(overfitting)이란? : over fit (적합하긴 하는데 과하게 적합하다. 그렇게 되면 좋은 모형이라고 할 수 없다) / 특정데이터에만 잘맞는 것이다. 나머지 데이터 셋에는 안맞는 경우

    -   모형 1 / 모형 2 --\> 모형1: 오차가 어떤 데이터셋에도 일정함. / 모형2: 오차가 0이였다가 급격히 증가함. then 모형1이 더 좋은 모델이라고 할 수 있다.

    -   오버피팅(overfitting) : 특정 데이터에만 잘 적용, 과적합

-   언더피팅(underfitting)

3.  교차검증(cross-validation)

Cross validation?

Total data에서는 모형을 만들어도 모형평가가 불가능하다!

모형을 평가하려면 우리가 가지고 있는 데이터말고 새로운 데이터로 모형을 평가해야하기 때문이다. 모형을 만들때 이미 우리가 가지고 있는 데이터로 기반으로 했기때문에 그 데이터를 토대로 평가를 하면 당연히 좋게 나온다.

그래서 입문자들이 많이 하는 실수가 모형을 만들때 사용했던 데이터로 모형평가를 하는 것이다.

-   모형 생성 시 사용했던 데이터는 정확도 측정에 사용하면 안된다! (주의사항)

Then 모형평가를 어떻게 합니까? 라고 물으시면 Total data -\> Train data(학습) / Test data(평가) 로 나누면 된다.

Train data(학습) --\> 모델 생성

Test data(평가) --\> 모델 정확도 측정 (모형평가)

But, Test data(평가)가 오버피팅이 나는 경우이면?

-   테이스 데이터를 사용하는 경우 오버피팅 주의!!

\--\> 내가 사용한 테스트 데이터가 오버피팅으로 인해 결과가 잘 나온 것이면 어쩌지?

Then Test data는 그대로 두고, Train data --\> Train data / Validation(검증데이터) 으로 나눈다.

Train data -\> 모델링 한 후

Validation data(검증데이터) -\> 모델 수정 및 평가 한 후

Test data -\> 정확도 측정 (최종 모델 평가)

-   Cross - Validation 방법(검증)

    -   Leave-one-out Cross - validation

    -   k - fold Cross - Validation (3가지 종류중 가장 많이 사용한다.)

    -   stratified(계층적) k - fold Cross - Validation

        -   클래스 비율 맞춰야한다.

-   머신러닝 전체 과정 요약

전체 데이터를

트레이닝 데이터 / 테스트 데이터로 나눈다. 그 후

트레이닝 데이터를 트레이닝 데이터와 검증 데이터로 나눈다.

트레이닝 데이터 -\> 모형 생성 / 검증 데이터 -\> parameter 설정 (이 과정을 여러 번 반복하며, cross - validation이라고 한다.)

그리고 이 과정을 통해서 최종 모형이 나오게 되고, 테스트 데이터를 통해서 최종 모형 평가를 한다.

4.  지도학습으로 무엇을 할 수 있을까?

-   분류(고객, 상품, 특성 등) / 예측(판매량, 트래픽(접속자 수), 추천)

-   이탈예측모형

-   유저 특성 별 분류

-   예측
