---
title: "Machine Learning(메타코드M, Ch2)"
author: "Lee"
date: "2023-01-09"
output: html_document
---

### Basic Math for ML

1.  **함수의 최솟값**

-   **함수의 최솟값에서의 미분값(순간 변화율)은 항상 0이다.**

-   이를 바탕으로 파라미터의 최적값을 구할 수 있다.

2.  **시그모이드 함수(sigmoid function)**

-   이진 분류 문제를 위한 비선형 함수

-   y = 1 / 1+e^-x^

-   함수의 출력값이 항상 0이상 1이하이며, 중앙 출력값은 0.5이다.

3.  **소프트맥스 함수(softmax function)**

-   다중 분류 문제를 위한 비선형 함수

-   y~i~ = e^x^~i~ / (K는 클래스 갯수)

### Linear Regression

1.  단순 선형 회귀(simple linear regression)

-   **피처의 종류가 한 개**인 데이터에 대한 회귀 모델

-   y = w~0~+w~1~x

2.  다중 선형 회귀(multiple linear regression)

-   **피처의 종류가 여러 개**인 데이터에 대한 회귀 모델

-   y = w~0~ + w~1~x~1~+w~2~x~2~+ ....+w~D~x~D~

3.  다항 회귀(ploynomial regression)

-   독립변수(피처)의 **차수를 높인** 회귀 모델

-   y = w~0~ + w~1~x + w~2~x^2^ + ..... + w~m~x^m^ --\> x^2^ , x^m^ : 새로운 변수로 봐도 무방하다.

### How to find optimal parameters?

1.  **(Remind) Parameter (= weight, 파라미터, 가중치)**

-   주어진 데이터(입력값)말고, 모델이 가지고 있는 **학습 가능한 파라미터**

Ex) w~0~, w~1~, w~2~ ...., w~D~

**Optimal (최적의) 이란 뜻은 데이터를 가장 잘 표현한다는 말과 동치이다.**

-   모델 예측값(y\^)과 실제값(y)의 차이가 가장 적은 모델

-   손실 함수값을 최소로 만드는 모델 파라미터

### Loss function (손실함수 정의)

**평균 제곱 오차(mean squared error, MSE)**

-   회귀 문제에서의 대표적인 손실 함수

-   **오차의 제곱의 평균**

-   L = $1/N\sum_{i=1}^{N}(y_i-y_i)^2$

### Least Square Method(1)

최소 제곱법(least square method)

-   최적의 파라미터를 구할 수 있는 한 방법으로, **데이터에 대한 오차를 최소화**하도록 함.

-   기울기 a와 절편 b의 일차 함수 ($L = \Sigma_{i=1}^{N}(y_i-(ax_i+b))^2$)

-   풀이방법 1

-   풀이방법 2

### (Remind) Linear Regression

단순 선형 회귀(simple linear regression)

-   피처의 종류가 한개인 데이터에 대한 회귀 모델

-   $y = w_0 + w_1x$

다중 선형 회귀(multiple linear regression)

-   피처의 종류가 여러 개인 데이터에 대한 회귀 모델

-   $y = w_0 + w_1x_1 + ...+w_Dx_D$

### Gradient Descent(1)

1.  **복잡한 함수의 경우**

-   다중 선형 회귀, 다항 회귀, 비선형 함수

-   최소 제곱법으로 해결 어려움

-   그러면 어떻게 최적의 파라미터를 찾을 수 있을까?

2.  **경사 하강법(gradient descent)**

-   손실 함수의 값을 최소화시키는 방향으로 파라미터를 업데이트하자!

### Gradient Descent(2)

1.  **경사 하강법(gradient descent)**

-   손실 함수의 값을 최소화시키는 방향으로 파라미터를 업데이트하자!

-   함수의 최솟값은 무조건 순간 변화율이 0이다!

-   손실 함수에 대한 미분값이 0이 되는 방향으로 파라미터의 업데이트 방향을 결정!

2.  슈도 코드(pseudo code)

-   현재 파라미터에서의 **손실 함수에 대한 미분값**을 구함

-   **미분값의 반대 방향**으로 파라미터값을 업데이트

-   미분값이 0이 될 때까지 1\~2번을 **에폭(epoch)[하이퍼파라미터]**만큼 반복
